### ISSUE TITLE
Wrong report URL if behind proxy

### ISSUE THREAD

**Issue by wasder** [kochetkov-ma/allure-server#15]
We host allure server behind nginx proxy and got wrong URL's to reports. If we change it manually it works. 
Is it possible to fix this on UI?

![image](https://user-images.githubusercontent.com/2205216/85702622-446e4780-b6e7-11ea-8548-ca91c34b528e.png)

**Comment by kochetkov-ma** [comment]
I will try to support manual proxy setting  through application.properies

**Comment by kochetkov-ma** [comment]
check [release 2.5.3](https://github.com/kochetkov-ma/allure-server/releases/tag/v2.5.3)
docker-compose
```  
environment:
         ALLURE_REPORT_URL_BASE: http://test.ru/ 
```
or `allure.report.url.base` in `application.properties`

**Comment by wasder** [comment]
Works perfect now.  Thanks a lot!
