### ISSUE TITLE
Configurable upload size

### ISSUE THREAD

**Issue by wasder** [kochetkov-ma/allure-server#16]
There is a hardcoded limit on upload size. Please make it configurable, through ENV properties.
https://github.com/kochetkov-ma/allure-server/blob/899f93e72807df89c22398f84e0fcb082a5246fb/src/main/resources/application.properties#L2

**Comment by kochetkov-ma** [comment]
You may replace dot to underscore in upper case:
`SPRING_SERVLET_MULTIPART_MAXFILESIZE=...` 
For example in docker-compose:
```
environment:
  SPRING_SERVLET_MULTIPART_MAXFILESIZE: 100MB
```
or adjust java options `-DSPRING_SERVLET_MULTIPART_MAXFILESIZE=100MB` when using `.jar`
see [spring boot cfg docs](https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding)

**Comment by kochetkov-ma** [comment]
In some situation external NGINX / PROXY or other servers can block request according to their constrains.
Did you manage to check my tips?

**Comment by kochetkov-ma** [comment]
out of date

**Comment by alexey107** [comment]
Works for me in 2.9.1 docker image.
just add to compose:
    environment:
      SPRING_SERVLET_MULTIPART_MAXFILESIZE: 250MB
      SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: 250MB
Thank you.
