### ISSUE TITLE
Add basic auth for GUI and API

### ISSUE THREAD

**Issue by Xotabu4** [kochetkov-ma/allure-server#17]
Hi! 
Really like your server! It simplifies my life a lot! 
But currently to cover my needs i need to setup nginx proxy with basic auth each time to protect this server atleast somehow from outside world.

Is it possible to add some simple login/password with credentials that will be specified thru env vars?

**Comment by kochetkov-ma** [comment]
Will plan it in the next minor version

**Comment by kochetkov-ma** [comment]
Add basic auth via settings `basic.auth.enable` / `basic.auth.username` / `basic.auth.password` . Readme updated.
Check please
[release 2.6.0](https://github.com/kochetkov-ma/allure-server/releases/tag/v2.6.0)

**Comment by Xotabu4** [comment]
@kochetkov-ma thank you so much! Will try this week.
