### ISSUE TITLE
Swagger not displayed in frame

### ISSUE THREAD

**Issue by frezot** [kochetkov-ma/allure-server#19]
Steps:

- `docker pull kochetkovma/allure-server:latest`
- `docker run -p 8080:8080 kochetkovma/allure-server:latest`
- open http://127.0.0.1:8080/ui/swagger in chrome/ff
- see the console

Result
```
swagger:1 Refused to display 
'http://127.0.0.1:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config' 
in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by kochetkov-ma** [comment]
Unfortunately new Chrome and Firefox introduced a similar protection. Firefox can at least be explicitly allowed to show, but chrome isn't. I will try to find a solution

**Comment by kochetkov-ma** [comment]
Fixed Spring Security options
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.6.1

**Comment by frezot** [comment]
👍
