### ISSUE TITLE
Unable to access report via friendly URL based on path, can only access generated report via long UUID-based URL

### ISSUE THREAD

**Issue by cstrong** [kochetkov-ma/allure-server#22]
Thank you for making this extremely useful piece of software.   I followed the instructions in the README and was able to generate a report.  My report is accessible via UUID at `http://localhost:8080/allure/reports/3f5cb933-ea58-46f5-b1ed-c64a5e2a0a00/`
I used the Swagger and found the response was 

```
     {
       "uuid": "3f5cb933-ea58-46f5-b1ed-c64a5e2a0a00",
       "path": "master/666",
       "url": "http://localhost:8080/allure/reports/3f5cb933-ea58-46f5-b1ed-c64a5e2a0a00/"
     }

```
Which showed me the URL.
I used the exact syntax provided by the README example, so I expected to _also_ be able to access this report from the friendly UI based on the path:  `http://localhost:8080/allure/reports/master/666/index.html`
However this results in 404 error.
I have never used this project before, so I am not sure if it is possible the README is out of date, or whether there is a regression.
Even without the friendly URL, it is working well for me.  But the friendly URL would be a really nice addition, if it can be made to work easily.   Please let me know, thank you!

**Comment by kochetkov-ma** [comment]
First of all thank you for your interest in the project! 

Previously, access to the report was based on path and to the last actual one. However, as part of the issue https://github.com/kochetkov-ma/allure-server/issues/20, I switched to uuid instead of path because a lot of reports may have the same path. Apparently both options should be supported. I will add it in the next release and fix the doc

**Comment by cstrong** [comment]
sounds good!
I agree that both are important.  It is great to be able to always get to the very latest report easily
But then you can use the GUID based URLs to get to the previous reports

**Comment by PraveenSamaSky** [comment]
May I know when can I expect the fix for accessing the report based on path is going to be available?
This is critical for me as I can just bookmark specific url in my dashboard to be always the latest when my stakeholders see it.

Thanks so much for your efforts.

**Comment by kochetkov-ma** [comment]
> May I know when can I expect the fix for accessing the report based on path is going to be available?
> This is critical for me as I can just bookmark specific url in my dashboard to be always the latest when my stakeholders see it.
> 
> Thanks so much for your efforts.

On vacation now. Will do by 23 January

**Comment by kochetkov-ma** [comment]
done. check please https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.0

**Comment by kochetkov-ma** [comment]
Generator response has new field `latest` with path based url.
In UI active report is shown as path based url then redorect to uuid url.
In UI you may `copy link` in browser context menu to obtain path based url before redirect

**Comment by cstrong** [comment]
Unfortunately the new version is failing on startup.   We don't have postgres.  What should we be passing in as environment variables?
here is our error message:
2021-01-22 04:14:2409:14:24.980 [main] WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator [132] - HHH000342: Could not obtain connection to query metadata
2021-01-22 04:14:24org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-200]
2021-01-22 04:14:24 at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)

**Comment by kochetkov-ma** [comment]
By default it uses H2 as before. Please create a new issue with full log and your configuration. Do you use docker image or stanalone?

**Comment by cstrong** [comment]
We are using the docker image.  Found the issue-- we are using a DB file created in 2.7.1   the new 2.8 version does not work with it.
see [issue 24](https://github.com/kochetkov-ma/allure-server/issues/24)

**Comment by PraveenSamaSky** [comment]
> done. check please https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.0

Many Thanks Maxim Kochetkov. It is working as expected.

**Comment by cstrong** [comment]
This works perfectly in 2.8.2, thanks very much!!
