### ISSUE TITLE
Bump allure version

### ISSUE THREAD

**Issue by wasder** [kochetkov-ma/allure-server#23]
https://github.com/kochetkov-ma/allure-server/blob/863173e37d0206119a2577419a2c4b1e400b2d0c/gradle/dependencies.gradle#L18
to the latest 2.13.8

**Comment by kochetkov-ma** [comment]
Good suggestion!

Will update the dependencies in the next release

**Comment by kochetkov-ma** [comment]
done. check please https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.0
