### ISSUE TITLE
Docker container for 2.8.0 fails to start using DB file created with version prior to 2.8.0

### ISSUE THREAD

**Issue by cstrong** [kochetkov-ma/allure-server#24]
**Step 1 run version 2.7.1  (/tmp/allure/ is empty):**
```
docker run  -v /tmp/allure:/allure/ -it kochetkovma/allure-server:2.7.1 -e allure.results.dir=/tmp/allure/
jornjambers@Jorns-MacBook-Pro allure % ls
db.mv.db	plugins
jornjambers@Jorns-MacBook-Pro allure % pwd
/tmp/allure
```

**Step 2 run 2.8.0 with same volume:**
```
docker run  -v /tmp/allure:/allure/ -it kochetkovma/allure-server:2.8.0 -e allure.results.dir=/tmp/allure/
And you will get Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-200]

```

**Comment by kochetkov-ma** [comment]
Unfortunately I can not reproduce. 
Could you provide the full console output of the container and, if possible, the H2 database file

**Comment by cstrong** [comment]
I’m able to reproduce again. The bug occurs when this file db.mv.db  was create with a version prior than 2.8.0 in our case 2.7.1.
So I just run these 2 commands with an local empty dir: /tmp/allure/ :
docker run  -v /tmp/allure:/allure/ -it kochetkovma/allure-server:2.7.1 -e allure.results.dir=/tmp/allure/
Then stop this (kochetkovma/allure-server:2.7.1)
And then run version 2.8.0 using the same directory
docker run  -v /tmp/allure:/allure/ -it kochetkovma/allure-server:2.8.0 -e allure.results.dir=/tmp/allure/
`reproduce_bug_allure.2.8.0.log
jornjambers@Jorns-MacBook-Pro allure % ls
jornjambers@Jorns-MacBook-Pro allure % pwd
/tmp/allure
jornjambers@Jorns-MacBook-Pro allure % docker run -v /tmp/allure:/allure/ -it kochetkovma/allure-server:2.7.1 -e allure.results.dir=/tmp/allure/
. 
:: Spring Boot :: (v2.3.3.RELEASE)
09:26:28.131 [main] INFO ru.iopump.qa.allure.Application [ 55] - Starting Application on 8ad64978641c with PID 1 (/allure-server-docker.jar started by root in /)
09:26:28.137 [main] INFO ru.iopump.qa.allure.Application [655] - The following profiles are active: default
09:26:30.003 [main] INFO org.springframework.data.repository.config.RepositoryConfigurationDelegate [127] - Bootstrapping Spring Data JPA repositories in DEFERRED mode.
09:26:30.003 [main] INFO org.springframework.data.repository.config.RepositoryConfigurationDelegate [127] - Bootstrapping Spring Data JPA repositories in DEFERRED mode.
09:26:30.166 [main] INFO org.springframework.data.repository.config.RepositoryConfigurationDelegate [187] - Finished Spring Data repository scanning in 140ms. Found 1 JPA repository interfaces.
09:26:30.166 [main] INFO org.springframework.data.repository.config.RepositoryConfigurationDelegate [187] - Finished Spring Data repository scanning in 140ms. Found 1 JPA repository interfaces.
09:26:31.403 [main] INFO org.springframework.boot.web.embedded.tomcat.TomcatWebServer [108] - Tomcat initialized with port(s): 8080 (http)
09:26:31.403 [main] INFO org.springframework.boot.web.embedded.tomcat.TomcatWebServer [108] - Tomcat initialized with port(s): 8080 (http)
09:26:31.431 [main] INFO org.apache.coyote.http11.Http11NioProtocol [173] - Initializing ProtocolHandler ["http-nio-8080"]
09:26:31.432 [main] INFO org.apache.catalina.core.StandardService [173] - Starting service [Tomcat]
09:26:31.434 [main] INFO org.apache.catalina.core.StandardEngine [173] - Starting Servlet engine: [Apache Tomcat/9.0.37]
09:26:31.591 [main] INFO org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] [173] - Initializing Spring embedded WebApplicationContext
09:26:31.594 [main] INFO org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext [285] - Root WebApplicationContext: initialization completed in 3316 ms
09:26:31.594 [main] INFO org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext [285] - Root WebApplicationContext: initialization completed in 3316 ms
09:26:32.864 [main] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor [181] - Initializing ExecutorService 'applicationTaskExecutor'
09:26:32.864 [main] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor [181] - Initializing ExecutorService 'applicationTaskExecutor'
09:26:32.994 [task-1] INFO org.hibernate.jpa.internal.util.LogHelper [ 31] - HHH000204: Processing PersistenceUnitInfo [name: default]
09:26:33.238 [task-1] INFO org.hibernate.Version [ 44] - HHH000412: Hibernate ORM core version 5.4.20.Final
09:26:33.879 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [113] - Found plugins directory allure/plugins
09:26:34.214 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=behaviors, name=Behaviors aggregator, description=The aggregator adds behaviors tab to the report, extensions=[io.qameta.allure.behaviors.BehaviorsPlugin], jsFiles=[index.js], cssFiles=[]) plugin
09:26:34.231 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=custom-logo, name=Custom logo aggregator, description=The aggregator replaces default Allure logo with a custom one, extensions=[], jsFiles=[], cssFiles=[styles.css]) plugin
09:26:34.273 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=jira, name=Jira Plugin, description=The plugin that adds support for Jira integration., extensions=[io.qameta.allure.jira.JiraExportPlugin], jsFiles=[], cssFiles=[]) plugin
09:26:34.298 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=packages, name=Packages aggregator, description=The aggregator adds packages tab to the report, extensions=[io.qameta.allure.packages.PackagesPlugin], jsFiles=[index.js], cssFiles=[]) plugin
09:26:34.307 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=screen-diff, name=Screen diff, description=Who cares about description by just-boris, extensions=[], jsFiles=[index.js], cssFiles=[styles.css]) plugin
09:26:34.336 [task-1] INFO org.hibernate.annotations.common.Version [ 49] - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
09:26:34.346 [main] INFO ru.iopump.qa.allure.helper.AllureReportGenerator [121] - Found PluginConfiguration(id=xray, name=Xray Plugin, description=The plugin that adds support for Xray integration., extensions=[io.qameta.allure.xray.XrayTestRunExportPlugin], jsFiles=[], cssFiles=[]) plugin
09:26:34.737 [task-1] INFO com.zaxxer.hikari.HikariDataSource [110] - HikariPool-1 - Starting...
09:26:35.222 [task-1] INFO com.zaxxer.hikari.HikariDataSource [123] - HikariPool-1 - Start completed.
09:26:35.269 [task-1] INFO org.hibernate.dialect.Dialect [170] - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
09:26:35.898 [task-1] INFO org.hibernate.validator.internal.util.Version [ 21] - HV000001: Hibernate Validator 6.1.5.Final
09:26:37.193 [task-1] INFO org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator [ 52] - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
09:26:37.214 [task-1] INFO org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean [416] - Initialized JPA EntityManagerFactory for persistence unit 'default'
09:26:37.214 [task-1] INFO org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean [416] - Initialized JPA EntityManagerFactory for persistence unit 'default'
09:26:38.221 [main] WARN org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration [220] - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
09:26:38.221 [main] WARN org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration [220] - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
09:26:38.746 [main] INFO org.springframework.security.web.DefaultSecurityFilterChain [ 43] - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@c35af2a, org.springframework.security.web.context.SecurityContextPersistenceFilter@64f1fd08, org.springframework.security.web.header.HeaderWriterFilter@42b28ff1, org.springframework.security.web.authentication.logout.LogoutFilter@43e1692f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@282ffbf5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@12c60152, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@44550792, org.springframework.security.web.session.SessionManagementFilter@6c15e8c7, org.springframework.security.web.access.ExceptionTranslationFilter@6cd56321]
09:26:38.746 [main] INFO org.springframework.security.web.DefaultSecurityFilterChain [ 43] - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@c35af2a, org.springframework.security.web.context.SecurityContextPersistenceFilter@64f1fd08, org.springframework.security.web.header.HeaderWriterFilter@42b28ff1, org.springframework.security.web.authentication.logout.LogoutFilter@43e1692f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@282ffbf5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@12c60152, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@44550792, org.springframework.security.web.session.SessionManagementFilter@6c15e8c7, org.springframework.security.web.access.ExceptionTranslationFilter@6cd56321]
09:26:41.200 [main] INFO org.atmosphere.cpr.AtmosphereFramework [610] - Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
09:26:41.201 [main] INFO org.atmosphere.cpr.AtmosphereFramework [611] - Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
09:26:41.256 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2840] - Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
09:26:41.275 [main] INFO org.atmosphere.util.ForkJoinPool [ 48] - Using ForkJoinPool java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
09:26:41.285 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1768] - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol
09:26:41.492 [main] INFO org.atmosphere.container.JSR356AsyncSupport [ 70] - JSR 356 Mapping path /ui
09:26:41.523 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1225] - Installing Default AtmosphereInterceptors
09:26:41.524 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
09:26:41.525 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
09:26:41.526 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
09:26:41.527 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
09:26:41.529 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1231] - Dropping Interceptor org.atmosphere.interceptor.HeartbeatInterceptor
09:26:41.530 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
09:26:41.532 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
09:26:41.534 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
09:26:41.538 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
09:26:41.539 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
09:26:41.540 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1244] - org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
09:26:41.541 [main] INFO org.atmosphere.cpr.AtmosphereFramework [1234] - Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
09:26:41.541 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT
09:26:41.545 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT
09:26:41.550 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT
09:26:41.550 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT
09:26:41.551 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT
09:26:41.551 [main] INFO org.atmosphere.cpr.AtmosphereFramework [2631] - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT
09:26:41.552 [main] INFO o...
Coll`

**Comment by kochetkov-ma** [comment]
Fixed. 
Try `2.8.2` https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.2.
Also i recommend you to use docker-compose.yml for example https://github.com/kochetkov-ma/allure-server/blob/master/docker-compose-h2.yml

**Comment by cstrong** [comment]
Confirmed Fixed!  thanks so much!!!
