### ISSUE TITLE
Getting the error `curl: (26) couldn't open file "/allure-results.zip"`

### ISSUE THREAD

**Issue by rakeshnambiar** [kochetkov-ma/allure-server#26]
Getting the error `curl: (26) couldn't open file "/allure-results.zip"`.

Here's the whole command curl --location --request POST "http://my-allure-server/api/result" --form 'allureResults=@/allure-results.zip;type=application/zip'

**Comment by kochetkov-ma** [comment]
See [swagger docs](http://allure.iopump.ru/ui/swagger)

I use swgger generated curl command: `curl -X POST "http://allure.iopump.ru/api/result" -H  "accept: */*" -H  "Content-Type: multipart/form-data" -F "allureResults=@allure-results.zip;type=application/x-zip-compressed"`

And it works.
This is my archive:
[allure-results.zip](https://github.com/kochetkov-ma/allure-server/files/5868252/allure-results.zip)

For Java you may use gradle plugin https://github.com/kochetkov-ma/allure-server-gradle

**Comment by rakeshnambiar** [comment]
Thanks. The above command worked for me. Similarly the report generation is possible through the UI or swagger. However, when I try through the postman with the header `Content-Type: application/json` I am getting the error `HTTP Status 500 – Internal Server Error`. Should I use any kind of authentication?

**Comment by kochetkov-ma** [comment]
There are no any authentication by default. Only via `basic.auth.enable` explicity.
Result request should have `multipart/form-data` mime type with multipart parameter `allureResults` as file archive path with nested type `application/zip`. It's not trival job for postman but it can. https://technicalsand.com/spring-boot-multipart-file-upload-example-postman/

**Comment by sunaynat** [comment]
Uploading results from postman is giving me error "Required request part 'allureResults' is not present"

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/120369667/224937293-e0b032fb-3616-482a-88a0-bdf885854449.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/120369667/224937387-846d690e-f7a6-4fc1-b0e8-e05f1334d799.png">

I am not able to get what is the issue. Please can you help.
