### ISSUE TITLE
Prepared Github Action for posting to this server

### ISSUE THREAD

**Issue by Xotabu4** [kochetkov-ma/allure-server#27]
Hi!

Prepared github action that compresses results, sends them to server, and then triggers report generation. Returns URL to generated report.

https://github.com/kochetkov-ma/allure-server

![image](https://user-images.githubusercontent.com/3033972/113505119-8c0ee300-9545-11eb-895c-5a7de447d027.png)

![image](https://user-images.githubusercontent.com/3033972/113505125-916c2d80-9545-11eb-98f1-ed01fafcc78d.png)

**Comment by kochetkov-ma** [comment]
Thx!
Will add to documentation

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/commit/4336430b13898e88ab9b496763814389783d09d2
