### ISSUE TITLE
Ldap auth and projects

### ISSUE THREAD

**Issue by marintrooper23** [kochetkov-ma/allure-server#28]
Good day. Is it possible to attach ldap authorization to the server side to differentiate access to reports?
For example, I have 10 commands, each of them generates a report, it goes to the server. Team 1 enters the server (via ldap) and sees only its own report, but does not see the report of team 2.
This can be done by mapping the ad group. You may have to introduce the concept of a project in the server side of the product.

**Comment by kochetkov-ma** [comment]
If I work on this project as my main work, I could do it :) But now I just can offer https://docs.qameta.io/allure-testops/ - everything you need is there. At the main work, we are starting to use this solution. If you will communicate with them, tell that I advised you.
