### ISSUE TITLE
Problem with adding custom categories

### ISSUE THREAD

**Issue by werwolw** [kochetkov-ma/allure-server#29]
When trying to add the file `categories.json` to the directory `allure/results/` or `allure/reports/` custom categories do not appear in new allure-report.
My `categories.json` file:
`[
    {
        "name": "Stale tests (selectors)",
        "messageRegex": ".*Unable to locate element.*",
        "matchedStatuses": [
            "broken"
        ]
    },
    {
        "name": "Problems into cluster browsers",
        "messageRegex": ".*Timed out .* from renderer.*",
        "matchedStatuses": [
            "broken"
        ]
    },
    {
        "name": "Ignored tests",
        "matchedStatuses": [
            "skipped"
        ]
    }
]`

**Comment by kochetkov-ma** [comment]
Check this allure-results.zip
[allure-results-failed.zip](https://github.com/kochetkov-ma/allure-server/files/6561331/allure-results-failed.zip)

You must add your `categories.json` to your local allure-results directory yourself like example above.
Then make zip archive and pass to Alure Server

It works well. I close the issue
