### ISSUE TITLE
Сгенерированные отчёты

### ISSUE THREAD

**Issue by 7makes** [kochetkov-ma/allure-server#32]
Добавить возможность загрузки вручную сгенерированных отчётов или отображение вручную  сгенерированных из локальных каталогов.

**Comment by kochetkov-ma** [comment]
Maybe in the future

**Comment by kochetkov-ma** [comment]
in next major release

**Comment by 7makes** [comment]
когда ожидать следующий релиз?

**Comment by kochetkov-ma** [comment]
check please https://allure.iopump.ru/ui/  `Upload Report`

**Comment by 7makes** [comment]
Не было возможности ранее проверить. В ближайшее время проверю.
