### ISSUE TITLE
Attachments are always 0 B - empty file

### ISSUE THREAD

**Issue by wooyork** [kochetkov-ma/allure-server#34]
Hello. 
My results are having attachments. If I generate reports manually with allure generate they are added correctly, however, if I use your application generated report and go inside, all attachments are just empty files 0B.

Please fix, your tool is very nice but cant use it due to this bug.
Tnx

**Comment by kochetkov-ma** [comment]
in next major version

**Comment by kochetkov-ma** [comment]
cannot reproduce
