### ISSUE TITLE
Need a chart for kubernetes

### ISSUE THREAD

**Issue by leo985** [kochetkov-ma/allure-server#35]
Thanks for your work very much，need a chart file for kubernetes ，are there plans to provide it?

**Comment by kochetkov-ma** [comment]
Can't reproduce. Please, describe more details and, if possible, archive with the allure results

**Comment by kochetkov-ma** [comment]
Please, check: https://github.com/kochetkov-ma/allure-server/tree/master/.helm/allure-server
