### ISSUE TITLE
Пустой отчет при загрузке и генерации через UI

### ISSUE THREAD

**Issue by grybakov** [kochetkov-ma/allure-server#36]
Добрый день.

Воткнул docker образ как описано в https://hub.docker.com/r/kochetkovma/allure-server
Запустил.
Репорт загрузил ручками через UI. Сгенерировал отчет. Успешно.
Но отчет пустой (см.скрин).

![Снимок экрана от 2021-07-28 13-45-09](https://user-images.githubusercontent.com/25502386/127309784-e7b01fc7-13aa-43c5-8798-9c95e544a286.png)

Данные по прогону в отчете точно имеются т.к. для проверки был взят артефакт allure-report.zip из Jenkins (в нем через Allure | Jenkins plugin все отображается).

**Comment by andrey-zhilin** [comment]
У меня такая же проблема. Вручную сгенерированный через allure отчет открывается. Через allure-server ситуация как на скриншоте выше.

**Comment by andrey-zhilin** [comment]
> У меня такая же проблема. Вручную сгенерированный через allure отчет открывается. Через allure-server ситуация как на скриншоте выше.

Разобрался. Нужно было файлы с репортом засунуть в архив (report.zip - > json-файлы). А у меня внутри архива была папка с репортом, внутри который были файлы.  (report.zip - > report -> json-файлы)

**Comment by grybakov** [comment]
> > У меня такая же проблема. Вручную сгенерированный через allure отчет открывается. Через allure-server ситуация как на скриншоте выше.
> 
> Разобрался. Нужно было файлы с репортом засунуть в архив (report.zip - > json-файлы). А у меня внутри архива была папка с репортом, внутри который были файлы. (report.zip - > report -> json-файлы)

Хм. Да, у меня тоже было в папке. Перепаковал все то что есть (скрин). Появился тренд. Но кейсы не отображаются ()в катеригория/сьютах) и их кол-во "0".
![Снимок экрана от 2021-08-03 09-14-16](https://user-images.githubusercontent.com/25502386/127967002-3f034b11-1f64-4ec3-b5f0-daf1ced04990.png)
![Снимок экрана от 2021-08-03 09-09-12](https://user-images.githubusercontent.com/25502386/127967012-2a018a3c-c054-4656-bf1c-e7b7fc49ba9e.png)

**Comment by grybakov** [comment]
Моя ошибка состояла в том, что в использовал уже сгенерированный в jenkins allure отчет (т.е. тот что слежал в allure-report, вместо сырых данных из report).

Можно закрывать.

**Comment by kochetkov-ma** [comment]
@grybakov Всем привет. Нужно ли это внести в readme? Если да, то напишите плиз последовательность действий я добавлю `troubleshooting`. Можно даже сразу в формате `markdown` )

**Comment by andrey-zhilin** [comment]
Я бы добавил сноску в разделе Upload results 

> :warning: **Make sure that:**
> - archive contains raw allure results (not a generated report) 
> - allure results are located in the root of an archive (not inside a folder)
