### ISSUE TITLE
Report retention

### ISSUE THREAD

**Issue by mfominov** [kochetkov-ma/allure-server#38]
Hi, thx for this project.

This is kind a feature request for storage retention.
In my opinion u can make such retention options:

- time base, delete reports older that x-days
- storage base, delete old reports to free space according to % of free space in data directory
- report path base, delete reports older that x-days for specific path. As option add ability to path report retention policy with report payload.

Thx.

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/blob/master/README.md#cleanup-features-since-1100
