### ISSUE TITLE
allure report doesn't show steps

### ISSUE THREAD

**Issue by PraveenSamaSky** [kochetkov-ma/allure-server#45]
Many thanks for the docker image. It is incredibly useful.

One issue I am facing is, though I have steps in my script; the step is now showing up in allure report. Please let me know the issue.

`
@Feature("USER JOURNEY")
@Test
public void UserJourney_test() throws Exception{
    tag = new Tag(client, secret, territoryDP, testEnv);
    userTao = tag.getUserBuilder().build();
    componentGroup = ComponentGroup.USER_JOURNEY;
    Sign_Up();
    Sign_In();
}

@Description("Sign_Up")
@Step("Verify SignUp Journey")
private void Sign_Up() throws Exception {
    System.out.println("Sign_Up");
}

@Step("Verify SignIn Journey")
private void Sign_In() throws Exception {
    System.out.println("Sign_In...");

}`

**Comment by kochetkov-ma** [comment]
Apparently this is not a generation problem. You have something wrongly connected in your project's dependency settings and it's not handling annotations. You need to use Allurte documentation (https://docs.qameta.io/allure/#_gradle) and connect AspectJ
