### ISSUE TITLE
File to large to upload 

### ISSUE THREAD

**Issue by yuvals41** [kochetkov-ma/allure-server#52]
failing to upload file due to it's size:

```org.apache.tomcat.util.http.fileupload.impl.SizeLimitExeceededExecption: the request was rejected because its size (7188808349) exceeds the confiugred maximum (104857600)```

 need a way to increase file size to upload to the server in the docker container (maybe through an env)

**Comment by kochetkov-ma** [comment]
Hello, thank you for your interest in the project!

Please try the advice in [issue #42](https://github.com/kochetkov-ma/allure-server/issues/42#issuecomment-994758371)
