### ISSUE TITLE
Update the docker image to openjdk:17.0.1-jdk-slim-bullseye

### ISSUE THREAD

**Issue by DavidLe-earnin** [kochetkov-ma/allure-server#59]
Could you update the docker image to openjdk:17.0.1-jdk-slim-bullseye? For security reasons
Could you also update the software to using node 16? Since node 12 has been off support

**Comment by kochetkov-ma** [comment]
Will try

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.13.6
