### ISSUE TITLE
Declared environment variable ALLURE_CLEAN_AGEDAYS, not getting considered for cleanup.

### ISSUE THREAD

**Issue by sunaynat** [kochetkov-ma/allure-server#62]
Environment variables have been set as below.
 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/120369667/224994914-06a703a5-c7b2-49ba-8111-1e790e2d59c0.png">

Still when I start the server on my local, I am getting below message during startup and my config, doesn't get picked up. Am i doing something wrong here?

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/120369667/224993887-a6d70bfd-079a-432a-8cf6-83f5d3648ddd.png">

**Comment by kochetkov-ma** [comment]
was an issue in https://github.com/kochetkov-ma/allure-server/releases/tag/v2.11.3

what version do you use? use latest https://github.com/kochetkov-ma/allure-server/releases/tag/v2.11.4
and attach the logs with prefix `[ALLURE SERVER CONFIGURATION]`

**Comment by sunaynat** [comment]
Using https://hub.docker.com/r/kochetkovma/allure-server latest docker image. 

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/120369667/230043546-d049f9bd-5aa7-4bca-9a56-8c8954a11e7b.png">

echo $ALLURE_CLEAN_AGEDAYS gives 
120

**Comment by kochetkov-ma** [comment]
I passed this variables to container:
```yaml
  ALLURE_CLEAN_AGE_DAYS: 7
  ALLURE_CLEAN_PATHS_0_PATH: "main/create-report:e2e"
  ALLURE_CLEAN_PATHS_0_AGE_DAYS: 90
  ALLURE_CLEAN_PATHS_1_PATH: "master/create-report:e2e"
  ALLURE_CLEAN_PATHS_1_AGE_DAYS: 90
```

And I have this configuration in log
```
CleanUp policy settings:
{
  "dryRun" : false,
  "time" : "00:00:00",
  "ageDays" : 7,
  "paths" : [ {
    "path" : "main/create-report:e2e",
    "ageDays" : 90,
    "edgeDate" : "2023-03-24T13:11:57.347935"
  }, {
    "path" : "master/create-report:e2e",
    "ageDays" : 90,
    "edgeDate" : "2023-03-24T13:11:57.348381"
  } ],
  "minAge" : 7,
  "closestEdgeDate" : "2023-06-15T13:11:57.348457",
  "edgeDate" : "2023-06-15T13:11:57.348503",
  "notDryRun" : true
}
```

If your variables dont work it means they were passed to container incorrect. Check you variables in container shell by comman like `echo $ALLURE_CLEAN_AGE_DAYS`.
It is not allure server's problem at all
