### ISSUE TITLE
Path param should be allowed to exceed 20 chars.

### ISSUE THREAD

**Issue by Watcher24** [kochetkov-ma/allure-server#67]
First of all - I want to say thanks for sharing this project - it is very valuable.

Now my "issue":

Path param should be allowed to exceed 20 chars. 
(Ideally also would allow to contain "/". But I shouldn't mix up things.)

Limiting path to 20 makes it difficult to host multiple projects on the same allure server.

I aim to serve results of multiple projects for multiple branches and / or multiple pull-requests. 
Since path should not contain "/" - I aim to use path params with a patterns like these: 
- `$module-name_$branch` or 
- `$module-name_$PR-number`

The limit of 20 is reached quickly - would be nice to make it (much) longer.

**Comment by kochetkov-ma** [comment]
Set `max=120`. Check please [v2.11.5](https://github.com/kochetkov-ma/allure-server/releases/tag/v2.11.5)
