### ISSUE TITLE
Historical reports uploaded with curl shows last report having zero results

### ISSUE THREAD

**Issue by zlyuk13** [kochetkov-ma/allure-server#76]
Hi followed your documentation and perfromed the following steps:
1. Created a report from the Nightwatch tests using `nightwatch-allure` lib (https://nightwatchjs.org/guide/reporters/use-nightwatch-allure-reporter.html)
2. Used Junit reports folder from 1. and command bellow to generate allure-report
allure generate junit_reports --clean -o allure-report

3. Then zipped the report folder
zip -r allure-report.zip allure-report

4. Started server locally using java
java -jar -Dallure.support-old-format=true -DPORT=9080 allure-server.jar & disown

5. Upload zip file and grab uuid
curl -X POST 'http://localhost:9080/api/result' -H  "accept: */*" -H  "Content-Type: multipart/form-data" -F "allureResults=@./allure-report.zip;type=application/x-zip-compressed" | jq '.uuid'

6. Create report using UUID (ffebdfc0-bc5a-4ae1-b320-a01b452788de)
curl --location --request POST 'http://localhost:9080/api/report' --header 'Content-Type: application/json' --data-raw '{ "reportSpec": { "path": [ "master", "dash-1" ], "executorInfo": {"buildName": "#dash-1"}},"results": ["ffebdfc0-bc5a-4ae1-b320-a01b452788de"],"deleteResults": true}'
All reports
![image](https://github.com/kochetkov-ma/allure-server/assets/7439824/b3cf364c-a317-4e8d-ab54-38304f2ab6d4)

Manual upload of the `allure-report.zip`
![image](https://github.com/kochetkov-ma/allure-server/assets/7439824/e39f3674-b961-4ba1-a872-d6588e1c8928)

Upload using curl
![image](https://github.com/kochetkov-ma/allure-server/assets/7439824/1c20bae3-4f2c-4d74-a010-2f088e3424d5)

**Comment by kochetkov-ma** [comment]
cannot reproduce try last release https://github.com/kochetkov-ma/allure-server/releases/tag/v2.13.6
