### ISSUE TITLE
executor.json ignored ?

### ISSUE THREAD

**Issue by sergebagi** [kochetkov-ma/allure-server#83]
Hi team,
I noticed that even though executor.json file is part of the allure-result.zip, it is ignored by the allure server
For instance, my executor.json looks like this:
```
{
    "reportName": "Acme Report",
    "buildOrder": 202403310708,
    "name": "My Test Framework",
    "buildName": "Staging Test Run 2024-03-31T07:08:04 UTC"
}
```
- **reportName** is not substituted in the report at the top left. It still shows "ALLURE REPORT" but it should display "ACME REPORT".
- **name** is not substituted in the Executors section in Overview screen. Instead it seems "Allure server generated <timestamp>" is hardcoded.
- Regarding **buildName**, we can pass it to the POST /api/report call, so we can still control it. That's fine.

**Comment by sergebagi** [comment]
Also **buildOrder** does not display in the history graph on the X axis

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.13.8
