### ISSUE TITLE
Enhancement - Custom image

### ISSUE THREAD

**Issue by sergebagi** [kochetkov-ma/allure-server#84]
Enhancement - Is there way to easily replace the top-left image ? 
<img width="172" alt="Screenshot 2024-03-31 at 4 19 17 PM" src="https://github.com/kochetkov-ma/allure-server/assets/18695046/24c024c7-2c67-4f57-8a1f-925099c2cda0">

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.13.6
